### PR TITLE
Introduce DisplayLinkAnimation

### PR DESCRIPTION
**Pull request by b3ll**
Oops I messed things up, @jessegrosjean how's this for #7 ?

### CODE REVIEW

**Comment by jessegrosjean** [comment]
I think name is good and functionally looks good too. Let me switch over my project and see if I run into any issue.

**Comment by jessegrosjean** [comment]
Thanks again for considering this, but now that I've looked closer at the code it isn't a great fit for my use case. I'm also not sure it's a great fit for Motion ... the existing Animation classes are all very clear, this one seems a bit confusing.

I think much better for me would be if you just marked Animation as open so I could subclass in my own code.

More details:

1. Subclassing ValueAnimation and managing the associated value is confusing to me. For from/to style animations it makes perfect sense to manage a tweened value. But to just accumulate time into a CGPoint is confusing.

2. I think it would be clearer (and give me more control to clients) if instead of all the `value` logic the callback was just passed display link timing information directly. I would really like access to the AnimationFrame ideally.

3. The example isn't to compelling to me. More compelling I think would be a pan style interaction where the pan distance determines the circles scale. Normally this would be implemented directly outside Motion and driven by pan interaction callbacks. But it works/looks much better (at least on macOS) I integrate those sorts of interaction driven updates into Motion's display link tick.

Anyway, my vote is again to just mark Animation open for subclassing. I think that would be cleaner for my client code and also leave Motion cleaner and easier to understand.

**Comment by jessegrosjean** [comment]
Thinking more... thanks for listening to all my blah blah.

I'm not sure what the implications of making Animation `open` for all the optimization work you've done, probably not good! I think if we just renamed my original `BlockAnimation` to `OpenAnimation` then it would be cleaner for both my client code and for Motion.

```
public class OpenAnimation<State>: Animation {
    
    public var state: State
    
    private let callback: (State) -> State
    
    public init(state: State, callback: @escaping (State) -> State) {
        self.state = state
        self.callback = callback
    }
    
    public override func hasResolved() -> Bool {
        false
    }
    
    public override func tick(frame: AnimationFrame) {
        state = callback(state)
    }
    
    public override func stop(resolveImmediately: Bool = false, postValueChanged: Bool = false) {
        self.enabled = false
        
        if resolveImmediately {
            completion?()
        }
    }
    
}
```

The rename also makes the classes purpose pretty clear. It allows me to inject arbitrary animation logic into Motion in an efficient way. I can inject State and callback behavior. It's basically a subclass, but doesn't effect Motions performance.

**Comment by b3ll** [comment]
Yeah that all makes sense to me. The more and more I look at it, the more I don't want it. I can make it open, should clear things up nicely :) 

As for performance, I don't think it'd be that bad. I mostly do a lot of the forced optimization to avoid a lot of Swift's protocol witness lookups… for one-offs, I don't think it'd be that bad (nor would it slow down the framework as a whole).

**Pull request closed without merging**
